### ISSUE TITLE
Code refreshing

### ISSUE THREAD

**Issue by Mandera** [Rusketh/ExpAdv2#136]
It would be great if there was a button (ctrl + r as well?) to refresh the file in case it has been altered, more specifically if you've opened it with another IDE. At the moment you need to close the tab and the reopen it in order to refresh it.

**Comment by VINTproYKT** [comment]
@Ripmax Why not? I think it's good feature.

**Comment by VINTproYKT** [comment]
Solved via @665fd2e7a0f1d85c72c17fa5190e338a8fa24480!
