### ISSUE TITLE
Loading textures from external sources?

### ISSUE THREAD

**Issue by ArmyArmyCz** [Rusketh/ExpAdv2#153]
Hey, would it be possible to make the setDrawTexture function able to support downloading from external storages? i.e. http://www.armeeh.maweb.eu/wat.vtf

**Comment by thegrb93** [comment]
Afaik, you can't do that in garrysmod. I have seen mods such as pac3 which can load an image via html and get the texture from the html, but loading an external vtf is impossible.

**Comment by ArmyArmyCz** [comment]
Yeah, Szymekk told me that it is not possible with vtf, but he might do it with pictures.

**Comment by szymski** [comment]
I shouldn't show it here, but take this: https://dl.dropboxusercontent.com/u/73430511/ShareX/2015/01/2015-01-09_01-14-21.mp4
