### ISSUE TITLE
Validation Shortcut

### ISSUE THREAD

**Issue by Xanuch** [Rusketh/ExpAdv2#158]
Expression 2 has a nifty shortcut CTRL+Space to validate.
Why not the same in ExpAdv2 (Lemon2?)

Seriously, clicking a bar gets annoying after a while

**Comment by Orzlar** [comment]
This used to be the same for expadv2 but it was removed when the compiler changes were made and the validations are no longer instant. Maybe an option in settings to enable it, but I agree with it being disaved by defauly

**Comment by Orzlar** [comment]
Disabled by default*

**Comment by ArmyArmyCz** [comment]
It hasn't been dissabled, it has now a new shortuct which is Ctrl + P.

**Comment by szymski** [comment]
Since the code completion has been added, Ctrl+Space is used to open code completion window, like in common IDEs, e.g Visual Studio or Eclipse. I talked to Rusketh about it and it will not be changed. Now, as you can see in commit 39f7cb6, we use Ctrl+P for code validation.
