### ISSUE TITLE
hasValue(tab,val)

### ISSUE THREAD

**Issue by Damianu** [Rusketh/ExpAdv2#160]
https://gist.github.com/2ee6316b9e6c6bb07410 - LUA code for it
It just searches for some value in table, if it exists then it returns true..

Ps. Name's mama so fat she's the reason African kids are starving

**Comment by AdamName** [comment]
Damianu's so fat that when he wants go to toilet his grandma has to roll him to it.

**Comment by Ripmax** [comment]
sexy

**Comment by Ripmax** [comment]
Added, but horribly coded and untested.

**Comment by Rusketh** [comment]
Fixed and closed.
