### ISSUE TITLE
revoke finished cycle

### ISSUE THREAD

**Issue by Orzlar** [Rusketh/ExpAdv2#161]
using invoke in a coroutine, or foreach halts the loops once called.

**Comment by Rusketh** [comment]
delegate test = function(int i) return i
    foreach( int k; int i: numberArray(1,2,3,4,5))
        print( invoke(*number, test, i) )

Could not reproduce this issue.

**Comment by Orzlar** [comment]
Now it errors with "This is not the invoke you are looking for"

After some debugging, it only happens when the delegate you are invoking does not return anything,
