### ISSUE TITLE
attempt to compare nil with number

### ISSUE THREAD

**Issue by CaptainPRICE** [Rusketh/ExpAdv2#166]
When dealing with sound component (playURL), it sometimes breaks-down an entire EA2 (clientside).
[lua/expadv/components/sound.lua:236: attempt to compare nil with number](https://github.com/Rusketh/ExpAdv2/blob/master/lua/expadv/components/sound.lua#L236)
Fix it.

**Comment by ArmyArmyCz** [comment]
Well, this has been reported and "fixed" few days ago, but I'm getting it too. Seems like my client just recieves corrupted data from other's EA2s or something.

**Comment by szymski** [comment]
This has been fixed in b97a7fd
