### ISSUE TITLE
entity.isWeldedTo vehicle on client

### ISSUE THREAD

**Issue by Orzlar** [Rusketh/ExpAdv2#170]
running `entity E = entity().isWeldedTo()` throws error

```
Expression Advanced 2 - Suffered a clientside Script error:
lua/expadv/components/entity.lua:687: attempt to call field 'HasConstraints' (a nil value)
```

Only seems to be an issue on client.

**Comment by AdamName** [comment]
http://wiki.garrysmod.com/page/constraint/HasConstraints

`constraint.HasConstraints( Entity ent )` is server sided only.

**Comment by Orzlar** [comment]
Listed as shared on the expadv helper,

**Comment by Rusketh** [comment]
Flagged it as server side only.
