### ISSUE TITLE
Cant Dupe EA2 chips

### ISSUE THREAD

**Issue by vekenti** [Rusketh/ExpAdv2#174]
Cant dupe EA2 chips on multiple servers

**Comment by AdamName** [comment]
Have you tried turning your computer off and on again?

**Comment by Ripmax** [comment]
What do you mean by multiple servers, do you mean the issue is happening on only some servers or... what?

**Comment by thegrb93** [comment]
Conflicting versions maybe.

**Comment by AdamName** [comment]
Expression Advanced 2 IT Specialist talking. Have you tried turning your computer off and on again?

**Comment by Damianu** [comment]
I will do
[Stupid post]

**Comment by AdamName** [comment]
Expression Advanced 2 IT Specialist talking. Have you tried turning it off and on again?

**Comment by Rusketh** [comment]
I am closing this issue, You need to put more then 'can't dupe ea2 chips'.
