### ISSUE TITLE
stream.ReadData stream.WriteData

### ISSUE THREAD

**Issue by edgarasf123** [Rusketh/ExpAdv2#176]
Can you implement stream.ReadData stream.WriteData?
net.ReadString doesn't suffice because it only returns part of the string to the NULL character, anything after NULL character is not returned.

**Comment by Rusketh** [comment]
ExpAdv2's buffers use Garrys net.WriteTable() function that doesn't support sending data like this. We also even if this where possible it would not work with the stream objects we currently use.

**Comment by edgarasf123** [comment]
Rather writing 2 tables (types, values) you could write net data in this format:
```vcount, type, len, value, type, len, value, type, len, value ...```
and rather using ```net.WriteString```, ```net.ReadString```, you could use ```net.WriteData```, ```net.ReadData```, even for the string type itself.
It's less process expensive because ```net.WriteTable```, ```net.ReadTable``` has to do lots of parsing. And the message length is twice smaller as by using net.WriteTable.

```
if SERVER then
	util.AddNetworkString("TEST1")
	util.AddNetworkString("TEST2")
	timer.Simple(0.3, function()
		net.Start("TEST1")
		net.WriteInt(3,8)
		for i = 1, 3 do
			net.WriteString("string")
			net.WriteInt(6,32)
			net.WriteData("abcdef",6)
		end
		net.Broadcast()
	end)
	timer.Simple(0.3, function()
		net.Start("TEST2")
		net.WriteTable({ "string", "string", "string" })
		net.WriteTable({ "abcdef", "abcdef", "abcdef" })
		net.Broadcast()
	end)
else
	net.Receive("TEST1",function(len)
		print("\nTEST1: "..len)
		local count = net.ReadInt(8)
		for i=1, count do
			net.ReadString()
			local len =net.ReadInt(32)
			net.ReadData(len)
		end
	end)
	net.Receive("TEST2",function(len)
		print("TEST2: "..len)
		net.ReadTable()
		net.ReadTable()
	end)
end
```
gave the output
```
TEST1: 416
TEST2: 832
```
