### ISSUE TITLE
Recursion bug

### ISSUE THREAD

**Issue by EnLRED** [Rusketh/ExpAdv2#181]
http://pastebin.com/ZRrkDqg5
in this code, in function qs, where "print(A,"_",B)" B must be 11, but it equals 0.

**Comment by Rusketh** [comment]
Could you please provide more information?

**Comment by EnLRED** [comment]
This is algoritm of quick sort, and A is left border of array. For first qs() in recursion it must be equal 0, but for second it must be 11, or #stl. But it equals to 0.

**Comment by EnLRED** [comment]
So with argument number two in qs the same problem, for fist qs() it must be 1, but for second it must be 2. For second qs it just copy all parameters from first(the first param is the sorting array, it equals for all of qs())

**Comment by EnLRED** [comment]
Oh, sorry second parameter was not copied, but third copied.

**Comment by Rusketh** [comment]
I hate to break this to you but: https://github.com/Rusketh/ExpAdv2/wiki/Examples#sorting-arrays-and-tables

**Comment by Rusketh** [comment]
I take it this is an issue with recursive functions not having there own separate stack of memory.
