### ISSUE TITLE
ExpAdv2 does not mount on Debian SRCDS if the addon folder has capitals.

### ISSUE THREAD

**Issue by Crypt0p** [Rusketh/ExpAdv2#182]
Renaming the addon folder to all lowercase letters solves the issue.

**Comment by szymski** [comment]
I don't understand your issue. That's GMod's ailment.

**Comment by Crypt0p** [comment]
If the repo was renamed, it would prevent other users from having this issue.

**Comment by Ripmax** [comment]
we're not gonna resolve this, because it takes little to no skill to rename the folder.

**Comment by OpenToClose** [comment]
Then atleast mention it in the documentation.
