### ISSUE TITLE
EA2 goes nuts

### ISSUE THREAD

**Issue by Lodkagan** [Rusketh/ExpAdv2#184]
Writing something uncompilable on clientside in the drawScreen() event breaks pretty much everything that has to do with rendering. Tested this on Singleplayer and Multiplayer with the latest update.

For example:
``` 
client {
    function void test(vector2 A) {
    }
    
    event drawScreen() {
        test()
    }
}
```

**Comment by Rusketh** [comment]
I was unable to reproduce using your example code.

**Comment by Rusketh** [comment]
Since this issue has not been replyed to in 3 days, and because the issue can not be replicated it is closed.

**Comment by Orzlar** [comment]
This is an actual bug I've experienced it myself,  I'll debug it tonight after work and post a bit of code that causes it

**Comment by Orzlar** [comment]
Try this 
```
vector2 A
Client drawScreen() {
    drawBox( vec2(0,0), A) 
} 
```
If I'm right in what I think causes it,  this'll do it, 
If not I'll still test tonight
