### ISSUE TITLE
Request: Drop out Derma permission

### ISSUE THREAD

**Issue by Monskiller** [Rusketh/ExpAdv2#188]
Completely cut off the derma permission and have it pop for the owner only. 
It becomes annoying when someone works on a code using derma and other less experienced users get the popup and have no clue where it comes from or don't know how to disable it, but just complain.

Or worse, they refuse to disable it but still complain about the menu popping. I can't think of an use where these menus should come up for other clients, so I'd request to cut out ther permission entierly and have the render happen for just the owner.

**Comment by Rusketh** [comment]
That would make the derma component useless taking away the main reason as to why we added it. If you don't wan't derma to display on your client then do not enable the feature. What you wan't to be doing is checking the owner of the gate against the localplayer before making your derma popup.
