### ISSUE TITLE
Some hooks in lua

### ISSUE THREAD

**Issue by Damianu** [Rusketh/ExpAdv2#189]
Just some hooks(shared if possible) in lua(not for use in EA2, just lua, lua lua LUA):
-Compilation Failed
-Compilation Suceed
-Tick quota exceeded
-Maybe some more?

**Comment by AdamName** [comment]
+rep

**Comment by Rusketh** [comment]
a lua hook?

**Comment by Rusketh** [comment]
oops

**Comment by Orzlar** [comment]
They wanna be able to detect when a chip breaks by using a hook call..

**Comment by Rusketh** [comment]
https://github.com/Rusketh/ExpAdv2/blob/master/lua/expadv/core.lua#L497

**Comment by Damianu** [comment]
Oh, nvm then.
