### ISSUE TITLE
KeyPress() event and keyRelease() is broken

### ISSUE THREAD

**Issue by Obscurell** [Rusketh/ExpAdv2#190]
Thats events runs everytick when we press key and not release.

**Comment by Rusketh** [comment]
It does not run on tick, It runs once for every time a player releases a key, not just the owner.

**Comment by Obscurell** [comment]
but it runs multiply

**Comment by Orzlar** [comment]
```
server event keypress(player P, int K)
{
    if(P == owner()){ print(K) }    
}
```

output 
```
97
119
100
115
97
119
100
115
```

No duplicates for me.

**Comment by Rusketh** [comment]
Closing this.
