### ISSUE TITLE
Add HTTP requests to allowed features popup

### ISSUE THREAD

**Issue by adosikas** [Rusketh/ExpAdv2#193]
Since clientside requests can potentially be abused for a lot of very, very bad stuff, like getting IPs, banning any player, accessing servers on the local network and messing with the local router, anything that would start a clientsided request (incluing httpRequest, not just playing sounds from URL) should have a option to manually enable it, with appropriate wording about the danger, keeping logs on requested URLs and possibly a blacklistlist/filter to prevent at least some attack scenarios.
(Maybe even a whitelist/popup like "Request http://192.168.0.1/set_proxy.php?proxy=attacker.net ? [DENY][ALLOW][ALLOW 192.168.0.1/*]")

To retain functionalty one could make it fallback to a serverside request and send the data to the client when possible.

**Comment by Rusketh** [comment]
We are aware of this issue and have recently made it so all http based functions will reject any url containing an ip address. We do already plan on moving client side http requests over to a feature and a re looking into adding a blacklisting system.
