### ISSUE TITLE
Compile time

### ISSUE THREAD

**Issue by thegrb93** [Rusketh/ExpAdv2#202]
The compiler is extremely slow.

I have a chip with 900 lines that takes 15 seconds to validate and 20 seconds to upload/run. The e2 equivalent takes about 0.1 seconds.

I also found that comments alone take a huge amount of time. Here's an example http://pastebin.com/R2SiArQ0 takes about 5 seconds to validate and 7 seconds to upload/run.

**Comment by Rusketh** [comment]
Compile time is the quickest its going to get, please do not mention this again.

**Comment by thegrb93** [comment]
I'm going to have to leave this project if there's not going to be any attempt to optimize the compile time. It's impossible to develop my game when it takes 30 seconds to compile and run it.
