### ISSUE TITLE
netstream/Stream Propblems

### ISSUE THREAD

**Issue by qLoadingq** [Rusketh/ExpAdv2#204]
client
{
    netstream Stream = stream()
    Stream.writeColor(color(255,255,255,255)) // error at this line
}

Expression Advanced 2 - Suffered a clientside Script error:
lua/includes/util/color.lua:16: bad argument #1 to 'min' (number expected, got nil)

**Comment by Rusketh** [comment]
This issue will be fixed in the commit pending commit.
