### ISSUE TITLE
Request: some kind of @include: system

### ISSUE THREAD

**Issue by IronRoadkill** [Rusketh/ExpAdv2#219]
Just any way to have multi file programs that compile into one expression.

**Comment by Grissess** [comment]
...does [this](https://github.com/Rusketh/ExpAdv2/issues/53) [mean](https://github.com/Rusketh/ExpAdv2/issues/52) no? Having multiple files for code reuse is a killer feature, and [one I embraced quite readily with E2](https://github.com/Grissess/gmod-data/tree/master/Expression2/lib); I don't see how you could do a big undertaking or create a useful (userland) library without it. (For the record, copy-and-paste [can be quite combersome](https://github.com/Grissess/gmod-data/blob/master/Expression2/lib/command.txt), even barring documentation.)

Even a method to transclude files verbatim would be appreciated--AFAIK, this was E2's implementation, plus some sugar to allow other users to download the files individually.

I would imagine, by that token, this would be a "preprocessing step" like @define:, and so the "right" way to do it would probably be @include:--thus putting the comment here.
