### ISSUE TITLE
What is hookAdd good for?

### ISSUE THREAD

**Issue by Deviluc** [Rusketh/ExpAdv2#221]
I was wondering why there is a functionality to add hooks if they never get called by something. I'm aware of the fact that you can manually call them by hookCall, but why should I do so if could just call a function?
I would love to be able to add hooks like this:
```
function void printShootData(entity Ent, table BulletData) {
    print("Entity: " + Ent.model())
    printTable(BulletData)
}

hookAdd("GM:EntityFireBullets", "ShootTest", function (entity Ent, table BulletData) {printShootData(Ent, BulletData)})
```

**Comment by Rusketh** [comment]
The hook system is part of the util component. It acts exactly like the hook library inside garry's mod lua.  This hook system is completely independent to the executing gate and has no default functionality, it is provided for users to implement a hook system using there own hooks should they need to.

**Comment by Deviluc** [comment]
Wow, that sounds great so it is possible to call hooks globally, but can we await to see a functionality to call gmod lua hooks? I'm not a lua coder (more java and c) but I would be glad to help implementing this feature.

**Comment by Rusketh** [comment]
It is not possible to call hooks both globally and certainly not gmod hooks, this will not be implemented.
