### ISSUE TITLE
toWorldAng(..) - toLocalAng(..)

### ISSUE THREAD

**Issue by WMaster7** [Rusketh/ExpAdv2#225]
Error when using them (runtime)
```
Expression Advanced 2 - Suffered a serverside Script error:
EXPADV2:273: attempt to call a string value
```

Also, while on the subject, I want to give a suggestion for these.

For these functions you'll only need 2 angles instead of 2 angles and 2 vectors.
It may be anoying to write empty vectors in it all the time, it looks... messy.
Also I would much preffer the first parameter to be the originating angle, instead of the second.
This because it will be simular to entity.toWorld(A), entity.toLocal(A), since it takes its origin from the entity.

You could also think if you like these;
*angle.toWorld(A), angle.toLocal(A)*
Both returning angles, making it also easy to shift through spaces. ex. angle.toWorld(A).toLocal(A)

**Comment by Rusketh** [comment]
I can't seem to reproduce this error, Could you please double check your on the latest workshop or git version and post your code.

**Comment by WMaster7** [comment]
```
angle T1 = ang()
angle T2 = ang()
vector V1 = vec()
vector V2 = vec()
angle A1= toWorldAng(V1,T1,V2,T2)
```
or just any of these:
```
angle A2 = toWorldAng(vec(),ang(),vec(),ang())
toWorldAng(vec(),ang(),vec(),ang())
```
I don't know where to view my version in the editor or tool, but I have little time now, so I'll respond later today.
