### ISSUE TITLE
Hologram RagDoll Model Scaling 

### ISSUE THREAD

**Issue by qLoadingq** [Rusketh/ExpAdv2#226]
Just does not work 

Lines that don't work

hologram H = hologram()
H.setColor(color(255,0,0,255))
H.setModel(ply.model())
H.setScaleUnits(vec(3))

My Application below 

server
{
    table base
    foreach(int I ; player ply:players())
    {
        hologram H = hologram()
        
        H.setColor(color(255,0,0,255))
        H.setModel(ply.model())
        H.setScaleUnits(vec(3))
        base[ply,holo]=H
    }
    
    event think()
    {
        foreach(int I ; player ply:players())
        {
            int Dist = (ply.pos().distance(entity().pos())/100)+10
            angle Ang = (angle)(ply.pos()-entity().pos())
            int Yaw = Ang.getYaw()
            int Pitch = -Ang.getPitch()
            int CosPitch = cos(Pitch)
            int X = cos(Yaw) * Dist * CosPitch
            int Y = sin(Yaw) * Dist * CosPitch
            int Z = sin(Pitch) * Dist
            
            base[ply,holo].setPos(entity().pos()+vec(X,Y,Z))
        }
    }
}

**Comment by Rusketh** [comment]
Its because your using a player model. You need to use a prop or ragdoll model.
