### ISSUE TITLE
Quota info windows' bad position

### ISSUE THREAD

**Issue by ArmyArmyCz** [Rusketh/ExpAdv2#230]
If you change the resolution of the EA2 screen to 1024, the Quota info window is in the middle of your screen.

Screenshot: http://images.akamai.steamusercontent.com/ugc/713037426225167344/FD203A8FEF96A4F6F21C4CAEC750DFEDBEE52D4C/

**Comment by Rusketh** [comment]
Easy to fix, and will be fixed in the next commit.
