### ISSUE TITLE
draw3DQuad weird texture and flickering

### ISSUE THREAD

**Issue by adosikas** [Rusketh/ExpAdv2#233]
This code:

    client {
        event requestFeatures(){
            request3DRendering()
            return true
        }
        event draw3D(){
            if(canRender3D()){
                setRenderMat("models/debug/debugwhite")
                draw3DQuad(entity().toWorld(vec(-20,-20,50)),entity().toWorld(vec(-20,20,50)),
                    entity().toWorld(vec(20,20,50)),entity().toWorld(vec(20,-20,50)),color(255,255,255,255))
            }
        }
    }

yields this result:

![http://imgur.com/OydJEUs](http://i.imgur.com/OydJEUs.jpg)

notice the black shading one the corners, additionally it flickers black and white seemingly random (impossible to show as screenshot obviously).
Using draw3DBox works just fine, by that i mean solid white material.

Am i missing something? There isn't really much documentation regarding draw3DQuad.

**Comment by szymski** [comment]
draw3DQuad function is just a wrapper of original render.DrawQuad function (http://wiki.garrysmod.com/page/render/DrawQuad). It's bugged itself and we can't do anything.

**Comment by adosikas** [comment]
Sorry if this sounds rude, but i am not really satisfied with you just saying "we can't fix this so this issue is closed"

Why close this instead of marking "can't fix" or something?
Or at least mentioning it on the wiki that this behavior is "normal".

Are there any other functions that are broken that one should know about before making any more issues?
