### ISSUE TITLE
Component not being detected

### ISSUE THREAD

**Issue by DarkMuffinJoe** [Rusketh/ExpAdv2#236]
I just started writing a darkrp shipment component. But when i start the game it doesn't load and there are no errors. 
I've created file called darkrp.lua and placed it in garrysmod\lua\expadv\components folder. Here's the code so far.
```
local Component = EXPADV.AddComponent( "darkrp" , true )

Component.Author = "Cheeki Breeki"
Component.Description = "Adds basic darkrp support."

EXPADV.ServerOperators( )

Component:AddInlineFunction( "shipmentItem", "e", "s", "(@value 1:IsValid() and @value 1:Getcontents().name or \"error\")")
Component:AddFunctionHelper( "shipmentItem", "e", "Returns name of weapon inside the given shpiment.")
```

And btw. what's the difference between `e:` and `e`?

**Comment by thegrb93** [comment]
You have to load it. https://github.com/Rusketh/ExpAdv2/blob/6bfdc37bafd4c8d0b474b1f7d059f5ace2614a14/lua/expadv/core.lua#L422

e: means the function is called as a member function. e.g. entity(1).myFunction() rather than myFunction(entity(1)).

**Comment by DarkMuffinJoe** [comment]
Thank you! I thought that there's some nice automatic component loader.

**Comment by szymski** [comment]
You can also put the file into garrysmod\lua\expadv\components\custom and then it'll load automatically.
