### ISSUE TITLE
Issue: Shared Session Text Corrupting/Desynced

### ISSUE THREAD

**Issue by KomradeSpectre** [Rusketh/ExpAdv2#237]
Occassionally when in a shared code session with another person, certain lines of code will corrupt on either side, desyncing the session.

**Comment by DaedalusGame** [comment]
Note that it might only happen on high latency, I had 200+ ms ping when we tested it.

**Comment by ArmyArmyCz** [comment]
Not only on high latency, this happens to me pretty often.

**Comment by Rusketh** [comment]
The current session system is very complicated. This feature is too complicated and a fix for the desync issues is not going to happen. This feature is not going to be available in the new editor.
