### ISSUE TITLE
Server side & Client side question

### ISSUE THREAD

**Issue by EvilJanny** [Rusketh/ExpAdv2#238]
Hi,
Is there a way to transfer server side I/O values to client side? I would need it to for drawScreen text.

**Comment by Orzlar** [comment]
You can use Netstreaming.
An example can be found here : https://github.com/Rusketh/ExpAdv2/wiki/Examples

there is also an event called trigger, which returns the name and class of the triggering wire input

```
server {
    input number A

    event trigger(string Name, string Class) {
        netstream net = stream()
        net.writeNumber(A)
        net.broadcast("sync number")
    }
}
client {
    number A = 0
    netReceive("sync number", function(netstream net) {
        A =  net.readNumber()
    })
}
```

Code not tested as always, but should show you an idea of how to do it.

**Comment by EvilJanny** [comment]
Thank you very much, it worked fine. I remeber reading it from somewhere before, but I forgot where so thanks for the link too.

**Comment by EvilJanny** [comment]
Thank you very much, it worked fine. I remeber reading it from somewhere before, but I forgot where so thanks for the link too.
