### ISSUE TITLE
Issue: Sending a color over a netstream spits out a random lua error on usage of the color

### ISSUE THREAD

**Issue by KomradeSpectre** [Rusketh/ExpAdv2#240]
Upon attempting to use the color I had received from my netstream, I get the following Lua error.

lua/expadv/components/color.lua:93: attempt to perform arithmetic on field 'r' (a nil value)

**Comment by VINTproYKT** [comment]
I found out that problem is that keys of `Color` table are received as numbers (1, 2, 3, 4), not letters (r, g, b, a).

**Comment by VINTproYKT** [comment]
Fixed via #297
