### ISSUE TITLE
Request: HideChat function

### ISSUE THREAD

**Issue by KomradeSpectre** [Rusketh/ExpAdv2#246]
I would like to request a function to hide chat for playerchat events, seeing as there is not one currently. This would mitigate chat spam when attempting to control a gate through chat.

**Comment by ArmyArmyCz** [comment]
You can just simply return from playerchat event.

**Comment by KomradeSpectre** [comment]
Except in each attempt that I've tried that, it doesn't hide the chat.

**Comment by thegrb93** [comment]
return false I think.

**Comment by ArmyArmyCz** [comment]
You're suposed to return string there, and returning null should hide the chat. But for some reason the return seems to be broken.

**Comment by thegrb93** [comment]
```
	hook.Add( "PlayerSay", "Expav.Event", function( Player, Text, Team )
		local Result, ResultType = EXPADV.CallPlayerReturnableEvent( Player, "playerChat", Player, Text, Team )
		if Result and ResultType == "s" then return Result end
	end )
```
Return "" to hide chat.
