### ISSUE TITLE
writeFile() fails to save large strings

### ISSUE THREAD

**Issue by Extra-Mental** [Rusketh/ExpAdv2#247]
The writeFile() function works okay when saving a short string, but when trying to save a large string it saves as an empty text file. I have only tried this for server side file saving and haven't checked client side.
Also would it be possible to add an append function?

**Comment by Rusketh** [comment]
File funcs ran serverside will save files to the server not the client. Could this possibly be your issue?

**Comment by Rusketh** [comment]
It seems the max file size was set to 300 chars. This will be upped to 5000 in the next beta update.

**Comment by Extra-Mental** [comment]
Oh I'm sorry. When I created this issue, I assumed that the limit of 300 was in KB like with E2's limit and not character count.

**Comment by Pwnzo** [comment]
Why not just remove the limit completely?

**Comment by Extra-Mental** [comment]
Limitless would allow people to make large files to take up space on client or server storage and potentially max them out.

**Comment by bigdogmat** [comment]
I'd say add a limit to the server but make it so clients can change theirs.

**Comment by VINTproYKT** [comment]
~5 KB looks like a normal quota for EA2 purposes, so #247 fixes this

**Comment by bigdogmat** [comment]
Why was this closed? The limit on master is still 300.

**Comment by VINTproYKT** [comment]
What? Why?
