### ISSUE TITLE
DERMA BUG

### ISSUE THREAD

**Issue by Arwwarr** [Rusketh/ExpAdv2#249]
i copy from examples derma code
...................

client {
    dframe frame = dframe()
    frame.setPos(vec2(206,256))
    frame.setSize(vec2(200,160))
    frame.setTitle("Example Window!")
}

== Error in expadv2 script and in conzole

xpression Advanced 2 - Suffered a clientside Script error:
lua/expadv/context.lua:77: attempt to compare string with number

[ERROR] lua/vgui/dframe.lua:256: attempt to index field 'btnClose' (a nil value)
  1. unknown - lua/vgui/dframe.lua:256

[ERROR] lua/vgui/dframe.lua:256: attempt to index field 'btnClose' (a nil value)
  1. unknown - lua/vgui/dframe.lua:256

**Comment by VINTproYKT** [comment]
I don't get such error.
