### ISSUE TITLE
Issue: String Issues

### ISSUE THREAD

**Issue by KomradeSpectre** [Rusketh/ExpAdv2#250]
I've noticed there are quite a few problems with the string methods, a couple i've run into brickwalls with are as follows:

1. Attempting to grab the name of another player's E2 via EA2 returns something along the lines of entity[%i]entity[%i].

2. While using the method player.tool(), using the method on a player other than yourself returns a lua error about it being a nil value and crashes the gate.

**Comment by Rusketh** [comment]
could you please provide an example code for the first issue.

**Comment by KomradeSpectre** [comment]
Excuse my likely terrible code.

client{
    array Chips = entityArray()
    function void Interval(){
        timerCreate("Interval",2,1,(delegate)Interval)
        Chips = findByClass("gmod_wire_expression2")
        Chips.connect(findByClass("expadv_gate"))
        
    }
    event requestFeatures(){
        
        requestHUD()
        return true
        
    }
    event drawHUD(number Width,number Height){
        
        for(number I = 1;#Chips;1){
            
            vector2 Vec = toScreen(Chips[I,entity].worldSpaceCenter())
            setDrawColor(color(255,255,255).setAlpha(255))
            if(Chips[I,entity].class() == "gmod_wire_expression2"){
                
                setDrawColor(color(255,255,255))
                setDrawTexture("beer/wiremod/gate_e2")
                drawTexturedBox(Vec+vec2(-10,-10),vec2(20,20))
                setDrawColor(color(255,255,255))
                array E2PolyArr = vector2Array(Vec+vec2(-10,10),Vec+vec2(10,10),Vec+vec2(10,-10),Vec+vec2(-10,-10))
                drawPolyOutline(E2PolyArr)
                setFont("Tahoma",12)
                setFontColor(color(255,255,255))
                drawText(Vec+vec2(-5,-5),"E2")
                drawText(Vec+vec2(-5,-24),((string)Chips[I,entity]))
            }
            elseif(Chips[I,entity].class() == "expadv_gate"){
                
                
                setDrawColor(color(255,255,255))
                setDrawTexture("mandrac/wire/e3")
                drawTexturedBox(Vec+vec2(-10,-10),vec2(20,20))
                setDrawColor(color(255,255,255))
                array EA2PolyArr = vector2Array(Vec+vec2(-10,10),Vec+vec2(10,10),Vec+vec2(10,-10),Vec+vec2(-10,-10))
                drawPolyOutline(EA2PolyArr)
                setFont("Tahoma",12)
                setFontColor(color(255,255,255))
                drawText(Vec+vec2(-8,-5),"EA2")
                drawText(Vec+vec2(-8,-24),((string)Chips[I,entity]))
            }  
            setFont("Tahoma",16)
            setFontColor(color(255,255,255))
            drawText(Vec+vec2(0,10),"Owner: " + Chips[I,entity].owner().name())
            
        }     
    }
timerCreate("Interval",0.1,1,(delegate)Interval)
}

**Comment by KomradeSpectre** [comment]
The reason I attempted to cast the entity to a string is that using entity.name() would crash the chip because it returned a nil value.

**Comment by VINTproYKT** [comment]
So, is it solved?
