### ISSUE TITLE
Outdenting/indenting last line causes an error stream

### ISSUE THREAD

**Issue by ElHyperion** [Rusketh/ExpAdv2#251]
Whenever I try to outdent/indent several lines, including the last one, I get an error stream of this:

[ERROR] addons/expadv2/lua/expadv/editor/ea_editor.lua:331: bad argument #1 to 'string_sub' (string expected, got nil)
  1. string_sub - [C]:-1
   2. GetSelection - addons/expadv2/lua/expadv/editor/ea_editor.lua:331
    3. PaintStatus - addons/expadv2/lua/expadv/editor/ea_editor.lua:1375
     4. unknown - addons/expadv2/lua/expadv/editor/ea_editor.lua:1368

The error happens only if you highlight at least one character, including at least one letter from the last line.

**Comment by VINTproYKT** [comment]
Same was with me when trying to outdent singleline in end of code. But now this error doesn't appear. :confused:

**Comment by ArmyArmyCz** [comment]
Found a way to kinda fix it, changing return text .. "\n" .. string_sub( self.Rows[stop.x], 1, stop.y - 1 ) to return text .. "\n" .. string_sub( self.Rows[stop.x] or "", 1, stop.y - 1 ). But indenting las line then causes the cursor to move to last line + 1, I wasn't able to fix that.

**Comment by ArmyArmyCz** [comment]
Found a way to fix it, need some more testing as I don't have time for it.
https://github.com/ArmyArmyCz/ExpAdv2/commit/2fff4d669b066d4ae6ef367ebff21ac7102fe651

**Comment by VINTproYKT** [comment]
@ArmyArmyCz 
You solve it!

**Comment by ArmyArmyCz** [comment]
I will once I get home, my code worked about fine, but I'll debug it a bit more.
