### ISSUE TITLE
Request: Shorter color declarations

### ISSUE THREAD

**Issue by ElHyperion** [Rusketh/ExpAdv2#253]
Why not make us able to declare colors the same short way as vectors? I mean things like vec(10), which equals vec(10,10,10), or vec() which stands for vec(0,0,0). Colors could work like color(255) for white, and color(255,128) for half-transparent white, thus equal to color(255,255,255,128)

**Comment by VINTproYKT** [comment]
:+1: , this must be useful.

**Comment by VINTproYKT** [comment]
Fixed via #297
