### ISSUE TITLE
Issue: getBackgroundColor function lua error.

### ISSUE THREAD

**Issue by KomradeSpectre** [Rusketh/ExpAdv2#254]
Upon attempting to use the function getBackgroundColor, the following error is thrown.

Compiler Error: EXPADV2:54: ')' expected (to close '(' at line 49) near 'surface'
Expression Advanced 2 - Failed to compile clientside:
EXPADV2:54: ')' expected (to close '(' at line 49) near 'surface'

**Comment by VINTproYKT** [comment]
There is no `getBackgroundColor` in `derma` component in ExpAdv2.
