### ISSUE TITLE
Issues with Adv2's on owner disconnect

### ISSUE THREAD

**Issue by Scors4** [Rusketh/ExpAdv2#258]
Basically, without fail today, every time an owner has left the (Granted, Spacetown RP) server and left an exp adv 2 behind, it has caused considerable lag until the owner either rejoins and removes it or it is cleaned up.

As of right now, neither appears to be applicable but the reason for that will be in another issue.

P.S. I also haven't had any luck with a self-removing clause on the chip.  Just fyi :)

**Comment by VINTproYKT** [comment]
It must be bad check system (no checks about exists owner or not), so it causes errors, if I'm right.

Can you please provide server logs or requesst it somehow from server hoster?

**Comment by Rusketh** [comment]
STRP is running the Beta branch, witch uses a modified performance system that doesn't work. this is not an issue with ExpAdv2 but with the Expadv2 beta.
