### ISSUE TITLE
OOP / User defined objects?

### ISSUE THREAD

**Issue by X-Coder** [Rusketh/ExpAdv2#261]
Is it currently possible to use some more oop style coding?
Like user defined objects or classes with vars+methods?

For example I want to define multiple rectangle objects and store them later in some array:

object rectangle = new object() // should create a new "userdefined" object called rectangle to which I can add my own properties or functions like
rectangle.x = 10 // Adds property x and initializes it to int 10
rectangle.y = 20 // Adds property y ...
rectangle.width = 100 // Adds property ... you get the idea
rectangle.height = 50
rectangle.GetHeight = function(){ return this.height } // Nice if it would support also functions

**Comment by X-Coder** [comment]
Forget what I just asked I just have found you already implemented tables support. Which basically doing the same.

**Comment by thegrb93** [comment]
There is some commented out code that attempts this, but from what the comments say, it had a lot of problems and was canceled.

**Comment by Rusketh** [comment]
Not possible.

**Comment by VINTproYKT** [comment]
I think it's possible with trust-include-a-like system. If validator can be optionally cutted off, you can include module files (containing class and something) without indexation (without variable.exists checks).
