### ISSUE TITLE
Opening a spawned chip creates a new tab

### ISSUE THREAD

**Issue by Extra-Mental** [Rusketh/ExpAdv2#262]
Opening a spawned chip creates a new tab in the editer, even if the code is the exact same in the previous tab. Then when you hit the save & close button, it asks what file to save it to.

**Comment by VINTproYKT** [comment]
Clicking "Save & Close" you just save your script to file (you don't need to select if already opened) and then close editor. Code must be manually uploaded into entity (gate, bot, screen).
