### ISSUE TITLE
acf setters not working

### ISSUE THREAD

**Issue by bladedpenguin** [Rusketh/ExpAdv2#267]
I can't seem to use acf setters. I can use acfactive() or acfthrottle() to get the activity or throttle state, but acfactive(true) won't turn an engine on  and acfthrottle(50) won't throttle up. I'm not sure whether this is an expadv2 or a acf problem, however. I did notice that acf r532 fixes starfall functions. I dunno if thats related. How can I start to debug this issue?

**Comment by Ripmax** [comment]
Is this using FreeeFry's ACF extension?

**Comment by MaZyGer** [comment]
I had these problems with expression2 too. Sometimes you have to use wirelink like WXL["Active", number] = 1

**Comment by bladedpenguin** [comment]
I didn't install any such thing, but apparently it made it into ACF in r543. I also submitted a bug report over there. I'd be interested in any insight you might have about why it's doing this, but if the problem is solely with Freefry's, then by all means close the issue.

It seems to affect native entity functions as well. I can launch a fridge with applyForce(vec(0,0,10000)), but it does nothing to a cannon.

**Comment by Ripmax** [comment]
If the functions are included in ACF then you will have to notify the ACF
team about the issue as we are unable to do anything about it.

**Comment by bladedpenguin** [comment]
There seems to be an issue with EXPADV.IsOwner(@value 1, Context.player)

**Comment by Rusketh** [comment]
I believe this has been fixed by the ACF team.
