### ISSUE TITLE
Using stream.writeVector2(Vector2) produces a serverside error.

### ISSUE THREAD

**Issue by Ricool06** [Rusketh/ExpAdv2#270]
Expression Advanced 2 - Suffered a serverside Script error:
lua/expadv/components/vector.lua:341: bad argument #1 to 'WriteFloat' (number expected, got nil)

For reference, I worked around the bug for now by casting the Vector2 as a Vector and dropping the Z coordinate.

Example:
<pre>
server{
    event clientLoaded(player ply){
            vector2 mapSize = getMapArea(1).getSize()
            netstream s = stream()
            s.writeVector2(mapSize)
            s.send(ply,"MAPSIZE")
        }
}
</pre>

**Comment by VINTproYKT** [comment]
Fixed via #299 

So, what's about casting? Can you please log your actions?

**Comment by bigdogmat** [comment]
He used 3D vectors instead of 2D vectors as a workaround, nothing is wrong with casting.
