### ISSUE TITLE
Entity.stress() Function?

### ISSUE THREAD

**Issue by Extra-Mental** [Rusketh/ExpAdv2#271]
There's a stress function for objects in lua and in Expression 2 I have made an extension to get the stress of an entity, I have used it for multiple things such as load balance on tank wheels and someone even suggested to make ABS steering with it.

It gets the pressure that the object applies to other things, like if you were to push a prop against the wall with the physgun it would raise the stress of the prop.

I would make it for EA2, but unfortunately I haven't quite understood how to code EA2 functions. So im requesting it here.

Wiki: http://wiki.garrysmod.com/page/PhysObj/GetStress

**Comment by ArmyArmyCz** [comment]
Fixed via #291
