### ISSUE TITLE
Player control functions?

### ISSUE THREAD

**Issue by Frez-M** [Rusketh/ExpAdv2#272]
it could be cool, if there could be some functions to control a player like setGod() or setHealth() and that kind of things. As well it would be cool, if there will be getters included. But of course, new "feature" could be added for all of that.

p.s. there's an extension for E2, which could be an example: http://steamcommunity.com/sharedfiles/filedetails/?id=216044582

**Comment by Extra-Mental** [comment]
You can use the conCommand() function to use admin mod console commands. Such as conCommand("ulx god ^") for ULX to god yourself.

**Comment by Rusketh** [comment]
I will not be adding this functionality in stock expadv2.

**Comment by VINTproYKT** [comment]
Sorry Rusketh, but I think this is good stuff (while making interactive things) and somebody may go throught to implement this in native way, so Expression Advanced will never be boring. Somebody, who is ready to do such enhancement in ExpAdv, please assign to this issue!

I don't have time, cause I'm now working on new wiki's structure. But will give some suggestions on this issue. So, try!

**Comment by ArmyArmyCz** [comment]
I don't think it's a good idea, especialy setting God & Health. Even if you make it as a feature, it could still be abused on RP/PVP servers.

**Comment by bigdogmat** [comment]
One of the main issues is this is hard to implement in a good way. Every admin mod handles god-mode differently from what I can see, and it'd be stupid to have checks for each of them. Also as @ArmyArmyCz said it could be abused easily, and so would have to be restricted heavily.

**Comment by Frez-M** [comment]
maybe it is possible to create an admin control menu, in which admins can set, which functions are allowed to normal players for use, or something like that.

**Comment by bigdogmat** [comment]
That still doesn't fix the issue that different admin mods would require different implementations which overall would be a mess.

**Comment by VINTproYKT** [comment]
Guys, I think if we will do extensions for EA2, we'd do it separated, so EA2 will still be independent. So you can play around with almost any different things, but separately from native EA2.

**Comment by Frez-M** [comment]
maybe some of the guys didn't really understand, what i meant: those functions "must" use native Lua functions like "ply.SetHealth()", but first it checks, if it's available for owner of ea2 to use it, but if not, ea2 can throw an exception at that place, where it is used. And I didn't mean it to do anything with admin mods.

**Comment by ArmyArmyCz** [comment]
We do understand, but if the owner set them self a god mode using this, the server could use a admin mod which has a different way of implementing god and because of that they couldn't ungod him. Also there's realy not an easy way to make it server owner friendly, we would either have to disable it as default and server owner would have to enable it or vice versa.
