### ISSUE TITLE
How on earth do you do a nil comparison?

### ISSUE THREAD

**Issue by johnsirett** [Rusketh/ExpAdv2#274]
My code is:
    Check.matchFirst("[0-9]+") == ""
to check whether a string is of conversible to a whole integer number.

But it doesn't work because matchFirst() returns nil on failing to find a match, not an empty string
In general: how would I do a nil comparison in ExpAdv2, since everything that touches nil seems to turn to crash?

**Comment by CaptainPRICE** [comment]
How about this (haven't tested at all, hopefully I have spelled it all right :smile: ):
```
server
{
input string InputString;
output string FirstMatch;
FirstMatch = ((string)InputString.matchFirst("%d+"));
print("Input:" + InputString + " (length=" + #InputString + ")");
print("First match:" + FirstMatch + " (length=" + #FirstMatch + ")");
}
```

**Comment by Rusketh** [comment]
string NoValue = lemon;
