### ISSUE TITLE
Validator doesn't accept a vector in entity.nearestPoint(vector)

### ISSUE THREAD

**Issue by Extra-Mental** [Rusketh/ExpAdv2#276]
When doing entity.nearestPoint(vector) the validator says no such method. When I remove the vector it validates but when the function gets used the chip crashes with an error of no return value.

The helper also shows that the functions use does not contain a vector argument, even though the description says "given position"

**Comment by Ripmax** [comment]
This should be fixed now, I will get Rusketh to update the workshop.

**Comment by VINTproYKT** [comment]
Fixed via #284
