### ISSUE TITLE
Stream.broadcast() confused to be Stream.send()?

### ISSUE THREAD

**Issue by Extra-Mental** [Rusketh/ExpAdv2#279]
In the Net Stream example in the wiki (https://github.com/Rusketh/ExpAdv2/wiki/Examples#net-stream) it displays that Stream.broadcast() accepts a player and string argument, however this code does not work until you remove the player argument.

I'm fairly sure that .broadcast() is used to send the net stream to all players and doesn't need a player argument, instead you would use .send(player, string). I think that the documentation may need to be fixed to prevent confusion of people new to EA2.

**Comment by ArmyArmyCz** [comment]
Just a mistage on the Examples page, fixed.
