### ISSUE TITLE
varargs (...) doesn't work

### ISSUE THREAD

**Issue by CaptainPRICE** [Rusketh/ExpAdv2#280]
```
server
{
    function void pass( bool b, ... ) // It says "Invalid use of vararg (...)" when there are more parameters (there are 2, so it will throw error on this line..).
    {
        // > How do I store varargs (...) into table or array? Tried couple of ways...
        //array a = variantArray( ... ) // Unexpected symbol (varargs).
        //table t = { ... } // Same error as above.
    }
    pass( false, 1, 2.5, "Hello", entity(), owner() ) // No errors here.
}
```

**Comment by bigdogmat** [comment]
It also seems unpack doesn't work, at least for printColor that is.

**Comment by Extra-Mental** [comment]
... means etc. Varargs are variable arguments meaning there can be many or few arguments that get passed through that function.

So you would want something like this:

    function void pass( bool b, int Number1, int Number2, string StringMessage, entity Ent, player Owner)

**Comment by bigdogmat** [comment]
I believe he used used it as an example to show they're broken...

**Comment by CaptainPRICE** [comment]
@Extra-Mental I know what they are and you have completely misunderstood the issue.
@bigdogmat Yes, you're right.

**Comment by VINTproYKT** [comment]
I think this is not supported operator (`...`) in ExpAdv2. I haven't found any docs on it.

**Comment by CaptainPRICE** [comment]
@VINTproYKT Not everything is documented. Wiki lacks it (or it was left out with a reason). See parser logic [here](https://github.com/Rusketh/ExpAdv2/blob/master/lua/expadv/compiler/parser.lua#L1651).

**Comment by Rusketh** [comment]
Var-Args are not actually supported in expadv2.
