### ISSUE TITLE
Add an option for enabling automatic outdent

### ISSUE THREAD

**Issue by ElHyperion** [Rusketh/ExpAdv2#283]
It would be useful to automatically undent the current line of the code whenever a right curly bracket is written, like in E2

**Comment by VINTproYKT** [comment]
Commited into `beta` branch! Actually, I don't know where to commit (beta or master), but outdent will be included in next release.

**Comment by ArmyArmyCz** [comment]
I don't think beta is being workshoped, if you make a working and tested code, commit it to master.

**Comment by VINTproYKT** [comment]
@ArmyArmyCz 
Hm, I have already commited #292 (so, it's merged into `Rusketh:beta` and closed now) and #293 (not merged yet). How should I act in this situation to merge down into `Rusketh:master`?

**Comment by ArmyArmyCz** [comment]
@VINTproYKT Just make a new pull request to merge into master and wait for someone (probably Szymski) to merge it. I'm not sure how often is Rusketh workshopping it.

**Comment by VINTproYKT** [comment]
Made a pull request into `master`.

**Comment by ArmyArmyCz** [comment]
Fixed via #297
