### ISSUE TITLE
no sign() function?

### ISSUE THREAD

**Issue by TimeSchocK** [Rusketh/ExpAdv2#288]
Searched for quite a while and couldn't find it. Does it have another name?

**Comment by VINTproYKT** [comment]
Thank you. Added `sign(n)` to `beta` branch.

**Comment by bigdogmat** [comment]
@VINTproYKT Only difference between beta and master should or at least from what I know be the time based op system, so these changes should be merged with both afaik.

**Comment by VINTproYKT** [comment]
@bigdogmat You mean that I need to commit these changes into both branches - `beta` and `master`?

**Comment by ArmyArmyCz** [comment]
@VINTproYKT There is no need to commit into both branches, if your new code is fully tested, just merge it into master.

**Comment by VINTproYKT** [comment]
Made a pull request into `master`.

**Comment by ArmyArmyCz** [comment]
Fixed via #297
