### ISSUE TITLE
Syntax error in expadv_screen.lua with new garrysmod update

### ISSUE THREAD

**Issue by X-Coder** [Rusketh/ExpAdv2#304]
I just updated my server (new garrysmod update, wire + wire extras) and now I get this error:
[Expression Advanced 2] lua/entities/expadv_screen.lua:220: no loop to continue near 'end'
  1. unknown - lua/entities/expadv_screen.lua:0
ERROR: Trying to derive entity expadv_scr_vgui from non existant entity expadv_screen!

I think "continue" doesn't belong into this hook, shouldn't it be "return" or something?

**Comment by bigdogmat** [comment]
This isn't caused by the new gmod update, but the update @Rusketh did to screens yesterday. 

[here] (https://github.com/Rusketh/ExpAdv2/blob/master/lua/entities/expadv_screen.lua#L220)he should've put return instead of continue.

**Comment by ArmyArmyCz** [comment]
Yeah, there should definetly be a return. Commiting right now.
