### ISSUE TITLE
Use LPeg for pattern matching

### ISSUE THREAD

**Issue by thegrb93** [Rusketh/ExpAdv2#306]
https://facepunch.com/showthread.php?t=750140

LPeg compiles patterns which speeds up pattern matching 1000 times fold. It also allows much more advanced patterns.

**Comment by Rusketh** [comment]
That's a binary, I can't force clients/server owners to install a binary module, I wouldn't be able to upload it to git or workshop either. Simple answer is if its done using a custom component then i'm down, but as stock that's a no.

**Comment by thegrb93** [comment]
You could make it optional. Similar to advdupe2's optional file buffer module.
