### ISSUE TITLE
how to change clip origin / setClipOrigin not working?

### ISSUE THREAD

**Issue by X-Coder** [Rusketh/ExpAdv2#311]
I try to get a fade out effect on my holo, but setClipOrigin does not seem to work for me. I'm doing something wrong? How can I change/move the clip position after it was created the first time?

When I increase -15 manually, I can see it is working the first time when the origin is set in pushClip.

```lua
server
{
    number Y = -15
    hologram holo=hologram("models/props_junk/TrashBin01a.mdl");
    holo.setPos(entity().pos()+vec(0,0,20))
    holo.setMaterial("models/wireframe")    
        
    function void createClip(){
        holo.pushClip(1, vec(0,0,Y), entity().up(), false)
        holo.enableClip(1, true)        
    }
    
    delegate increment = function(){
        Y+=1
        holo.setClipOrigin(1, vec(0,0,Y))
        print(holo.getMaterial())
    }     
    
    createClip()
    timerCreate("inc", 1, 0, increment)
}
```

**Comment by X-Coder** [comment]
Thank you, I will test it now.

Right before you changed this, I debugged the lua code. I figured you never seem to change ClipQueue table when I call for example functions like SetClipOrigin, so the tick function never calls SyncClient which will in return never call the SyncClips or SyncClipsForce function.

I think you have to add ClipQueue[ self ] = true to all functions like SetClipOrigin.

**Comment by X-Coder** [comment]
With your patch, the clipping has the wrong direction with my example code above.
I reverted your modification and created a patch in a fork which seems to work for me now.
Do you want to merge it back?

**Comment by Rusketh** [comment]
Make a pull request please.

**Comment by X-Coder** [comment]
Push request created. It will also revert your previous "global" fix as I don't know if my code is wrong and relates on the bug you previously fixed. With this revert+commit my result looks fine.
