### ISSUE TITLE
Error when trying to send a nil script to a player on PlayerInitialSpawn

### ISSUE THREAD

**Issue by Mista-Tea** [Rusketh/ExpAdv2#316]
```
[ERROR] addons/expadv2/lua/expadv/net.lua:24: attempt to get length of local 'string' (a nil value)
  1. writeCompressedString - addons/expadv2/lua/expadv/net.lua:24
   2. SendToClient - addons/expadv2/lua/expadv/net.lua:89
    3. unknown - addons/expadv2/lua/entities/expadv_base/init.lua:31
```

I have a feeling this is caused by removing an EA2 chip before the 5 second timer finishes on https://github.com/Rusketh/ExpAdv2/blob/master/lua/entities/expadv_base/init.lua#L28-L34 which doesn't have any checks to make sure the entity itself is still valid.

Probably need to add **```IsValid(self)```** on line 30.

**Comment by ArmyArmyCz** [comment]
I've added the IsValid check, could you please check if it still exists?

**Comment by Mista-Tea** [comment]
I'll update my repo and test it out later tonight. Will report the result back as soon as possible. Thanks!

**Comment by Mista-Tea** [comment]
I've tried to cause the error several times using a second account but it doesn't appear to be occurring, so I'd say ad57a1255ddf5884cb87902601ffb662ab78a70e fixed it.

I'll let you know if anything changes.
