### ISSUE TITLE
Variable/Class coloring in functions/events

### ISSUE THREAD

**Issue by El-Mico** [Rusketh/ExpAdv2#320]
When creating a function or event some variables and data types are colored incorrectly. As a guess, this may have something to do with how creating multiple variables at once is colored.

![image](https://cloud.githubusercontent.com/assets/11700686/12970359/d6252026-d05b-11e5-8a49-e17c3c3d93f0.png)

I only show functions in the image, but the same behavior can be found in creating events.

Thanks for your hard work!
ElMico

**Comment by ArmyArmyCz** [comment]
My guess is e27f491aca879fc077a686f4ab5d6f2ebd6d346d has to do something with it.

**Comment by Codingale** [comment]
For me a temporary fix is commenting around it such as `int Ghi, /* */`
