### ISSUE TITLE
Weird player class behavior

### ISSUE THREAD

**Issue by bigdogmat** [Rusketh/ExpAdv2#321]
I looked over the code in the player file and entity file to see if I missed anything, and I don't believe I have. I thought this had something to do with #319, though after testing it didn't.

In both cases my name on the server is "nyan"

```
server
{
    event PlayerSay(player Ply, string Text)
    {
        player Target = playerByName(Text.lower(), false)
        print("-- ", Target.name())
    }
}
```

>Input: kek
>Output:
>Input: an
>Output: nyan
>Input: kek
>Output: nyan
>Input: Nothing
>Output: nyan

As you can see it works as expected by returning nothing for the first output as kek doesn't match my name. On the next message I type a part of my name, and as expected it matches it me, and outputs my full name. 

Weird part comes when I type stuff that has nothing to do with my name and it still matches it. I believe it's an issue with the variable having a valid entity stored and then trying to overwrite it with a invalid entity, though I didn't see anything that disallowed that. Also it should be creating a new variable each time, though it seems to persist.

Next test script is this

```
server
{
    player kek

    kek = playerByName("kek", false)

    print(kek.name())

    kek = playerByName("Ny", false)

    print(kek.name())

    kek = playerByName("kek", false)

    print(kek.name())
}
```

I have the same name as before and the output is

>Output:
>Output: nyan
>Output: 

As seen here it works as expected and replaces the variable each time.

My best guess is I missed something in one of the files, though I don't believe I have. If I haven't then maybe it's an issue with scoping? I'm not completely sure about this

**Comment by ArmyArmyCz** [comment]
Should be fixed via 185d2d1e522c9af324fa5bcd27adb5ed06aaa0b5.

**Comment by bigdogmat** [comment]
I didn't think that would be needed because if the variable was never set then it shouldn't have been equal to an older search. 

If this fixed the issue that still means the compiler has a scoping issue. I may look into the compiler later and fix the issue

**Comment by ArmyArmyCz** [comment]
This fixed it, so it has to be scoping, but that's something I'm not able to fix.

**Comment by bigdogmat** [comment]
Actually thinking about it and looking back at the older code, it makes sense. 

I thought it created local variables, though if it did then the older code would've never been able to get "result" outside of the loop. Because of that I'm guessing it's creating a global variable in which case it being used inside an event it would've never created another unique variable name. Because of that the global was always there so if the loop found nothing then it'd use the last global
