### ISSUE TITLE
How to make holo's stay in the same position when a object its parented to rotates

### ISSUE THREAD

**Issue by SilentDeathTheSeal** [Rusketh/ExpAdv2#326]
when I try to parent a holo to a car and move it to an area on the car and then move the car it moves with the car but it doesn't stay in the same position I have a feeling it has something to do with this:
hologram(2).setPos(Car.pos() + vec(0,15,50))
but I don't know how to fix it

**Comment by ArmyArmyCz** [comment]
You would need to set the position relative to the car, but you just need to set the position once, parent it and you're good to go.

**Comment by SilentDeathTheSeal** [comment]
ah thanks
