### ISSUE TITLE
How do i make a timer repeat infinitley

### ISSUE THREAD

**Issue by SilentDeathTheSeal** [Rusketh/ExpAdv2#328]
when I try to do this:
server{
    number T
    timerSimple(1,function(){
        T = T + 1
        print(T)
        })
        }
I want it to loop infinitley but when i place it it only goes off once and stops

**Comment by bigdogmat** [comment]
Use timerCreate

```
number amount

timerCreate("kek", 1, 0,
    function()
    {
        amount += 1
        print(amount)
    }
)
```

**Comment by SilentDeathTheSeal** [comment]
ooooh so for it to loop repeatedly you set repetitions to zero?

**Comment by bigdogmat** [comment]
Yes

**Comment by SilentDeathTheSeal** [comment]
somethings odd about it when i placed it, it prints the previous number as well as the current number

**Comment by bigdogmat** [comment]
Are you running it shared?

**Comment by SilentDeathTheSeal** [comment]
shared?

**Comment by bigdogmat** [comment]
If you don't have the code wrapped in a server or client block then it's gonna run on both, ie shared. So the first number you're seeing is the one running on the server and the second one is the one from the client.

**Comment by SilentDeathTheSeal** [comment]
oh

**Comment by bigdogmat** [comment]
This can be closed now
