### ISSUE TITLE
How to use apply force so that it homes a prop to another prop

### ISSUE THREAD

**Issue by SilentDeathTheSeal** [Rusketh/ExpAdv2#329]
I've never used apply force before and I want to know how to use it to make a prop it spawns homes into another prop

here's the code i tried:
server{
    entity Link
    entity Link2
    number F
    Link = spawn("models/hunter/blocks/cube025x025x025.mdl",false)
    Link2 = spawn("models/hunter/blocks/cube025x025x025.mdl",true)
    Link2.setPos(entity().pos() + vec(0,100,50))
    event tick(){
        if(F == 1){
            Link.applyForce(Link2.pos())
            }
        }
    timerSimple(5,function(){
        F = 1
        })
    }
but after 5 seconds it just starts forcing itself into the ground instead of moving to the target
how would i make it home into the target?

**Comment by oOLinusOo** [comment]
you have to direction vector not a position vector if i remember right. try something like Link.applyForce(  (Link.pos()-Link2.pos())*force   )

**Comment by SilentDeathTheSeal** [comment]
Found out how to you got most of it right, however, you need to do this
Link.applyForce( (Link.pos()-Link2.pos())*force*-1 )
you need *-1 so it goes the right way instead of the opposite direction
