### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by its-suun** [Rusketh/ExpAdv2#330]
:warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning:
The script uploading is unsafe (see [net.lua](https://github.com/Rusketh/ExpAdv2/blob/master/lua/expadv/net.lua#L45)). It doesn't check for the uploader and everybody with some lua experience can overwrite other's chip. Can be pretty abused.
It even says in the code `-- TODO ^ That function!`. :|
:warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning:
Credits: Forsaken

**Comment by bigdogmat** [comment]
This could be fixed with a simple player is equal to owner check, I wonder why that wasn't done.

**Comment by its-suun** [comment]
I wonder why it still isn't done
