### ISSUE TITLE
Player.scrW() and Player.scrH() missing?

### ISSUE THREAD

**Issue by Extra-Mental** [Rusketh/ExpAdv2#332]
I havent been able to find any functions to get the resolution of a players screen other than using the drawHUD event, are they missing or are the egpScrW and H supposed to be accepting a player? because they error when i try to use a player entity in them.

**Comment by AkitakeKun** [comment]
Well egp technically is an external thing to expadv2, there is just compatibility in between the two.
Not sure if the two functions are supposed to accept a player, would need to check the E2Helper for that, and if it is in E2, it should be in EA2.

**Comment by bigdogmat** [comment]
By default there are no ScrW or ScrH functions in ExpAdv2.

egpScrW and egpScrH both take player arguments, though the value returned by them could be changed by the player as they're only set once.

https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_egp/lib/egplib/usefulfunctions.lua#L217-L237

They also require wiremod to be installed as they rely on its EGP code.

> and if it is in E2, it should be in EA2.

Incorrect
