### ISSUE TITLE
.onPaint() missing arguments for size of painted object.

### ISSUE THREAD

**Issue by Extra-Mental** [Rusketh/ExpAdv2#335]
The lua function gives width and height of the panel to be painted: [https://wiki.garrysmod.com/page/PANEL/Paint](url)

However when I use this code it errors saying number expected, got void.

```
Button.onPaint(function(int W, int H){  
       setDrawColor(color(255,255,255,200))
       drawBox(vec2(0),vec2(W,H))
})
```

**Comment by bigdogmat** [comment]
You can still get the size by using the getSize(I think that's what it's called) method, however I'll make a pr to add the arguments in the callback
