### ISSUE TITLE
Player.timeConnected() not working client side.

### ISSUE THREAD

**Issue by Extra-Mental** [Rusketh/ExpAdv2#336]
When i use Player.timeConnected() client side, it errors with this message:
Expression Advanced 2 - Suffered a clientside Script error:
EXPADV2:6: attempt to call method 'TimeConnected' (a nil value)

However it works fine server side.

**Comment by bigdogmat** [comment]
TimeConnected is defined as server side only in Gmod, however for some reason it's defined as shared here. So just use it server side
