### ISSUE TITLE
Panel:SetMouseInputEnabled( ) and Panel:SetKeyBoardInputEnabled( )  ???

### ISSUE THREAD

**Issue by oOLinusOo** [Rusketh/ExpAdv2#339]
Is there a way to set the input of a mouse and keyboard instead of using Panel.makePopup() ?
I would like to set the visibility of a panel to true and activate the mouse then but still be able to move my character. I´m not that good at expadv2 so I might have overlook the method ?!

oh btw. is there a way to get the visibility of a panel like Panel.isVisible() ?
I didn´t see something similar but as i said i´m just starting to code ExpAdv2 :)

**Comment by bigdogmat** [comment]
Panel.MakePopup calls both Panel.SetMouseInputEnabled and Panel.SetKeyboardInputEnabled, though ExpAdv2 doesn't have methods to call either one individually.

As for getting the Visibility, currently there aren't any methods to do so, though Panel.IsVisible could be

**Comment by oOLinusOo** [comment]
Ok so there is no way to do it at the current status of the addon ?! 

Thank you for your fast reply! 
Didn´t expect it that fast xD
