### ISSUE TITLE
Spawning holograms and tick quota exceeded

### ISSUE THREAD

**Issue by NanobotZ** [Rusketh/ExpAdv2#356]
I'm trying to run this code (on a server):
```
server {
    vector pos = entity().pos()
    for(int x = 1; 3; 1) {
        for(int y = 1; 3; 1) {
            for(int z = 1; 3; 1) {
                hologram holoG = hologram()
                holoG.setPos(pos + vec(x*15, y*15, z*15 + 20))
            }
        }
    }
}
```
and it exceeds tick quota at  x=2, y=3 and z=1.
My `expadv hologram rate` is set to 500, and `expadv hologram max` is set to 500. 
Is this a bug? I'm trying to spawn 27 holograms...

**Comment by Rusketh** [comment]
creating a hologram uses a lot of ops since your creating and registering an entity.

You can save some ops in that for loop though by using a vector loop.
`for(vector v = vec(1,1,1); vec(3,3,3); v3c(1,1,1)) {}`

**Comment by NanobotZ** [comment]
I've found out that using smaller/less-advanced/low-poly models works a lot better, I've managed to spawn ~100 holograms with sprops sphere_3. I've created a workaround for myself, I spawn my holos in a coroutine and when I'm close to exceeding limit (perf()), just sleep the coroutine for 0.05 second.

**Comment by VINTproYKT** [comment]
I remember those times when I have trying to do my snow machine, that spawns, oh my God, **high quality spheres** (ellipsoids) :open_mouth: , then I've managed to use average quality, but every time I spawned it - working not longer than 10 seconds, then throwing `tick quota exceeded`. :cry: Now I'm bored of Garry's mod :laughing: Happy coding, guys!
