### ISSUE TITLE
Netstream issues with vectors

### ISSUE THREAD

**Issue by Doubleumc** [Rusketh/ExpAdv2#361]
When using a netstream to send vectors both to or from a server those vectors can arrive in an altered form.  Specifically, this alteration appears to be a modulus of 16384.  This can be demonstrated by using the following program, tested in singleplayer on gm_freespace_13:
```
server {
    netstream Stream = stream()
    Stream.writeVector(vec(16385))
    Stream.send(owner(), "StC")
    
    netReceive("CtS", function(netstream ns) {
        vector Test = ns.readVector()
        print("CtS: ", Test)
    })
}

client {
    netstream Stream = stream()
    Stream.writeVector(vec(-16385 * 2))
    Stream.sendToServer("CtS")
    
    netReceive("StC", function(netstream ns) {
        vector Test = ns.readVector()
        print("StC: ", Test)
    })
}
```
In this code the client should receive `Vec( 16385.00, 16385.00, 16385.00 )` and the server should receive `Vec( -32770.00, -32770.00, -32770.00 )`.  Instead the output is this:
```
StC: Vec( 1.00, 1.00, 1.00 )
CtS: Vec( -2.00, -2.00, -2.00 )
```
Again, this _appears_ to be a modulus of 16384, but there could be other factors at work.  16384 is a very interesting number for a few reasons.  First it is a power of two, specifically 2^14 -- maybe some bits are being truncated through the netstream.  Second it is equal to the square of 128.  Third and perhaps most interestingly, +/-16384 are the map borders on gm_freespace_13.  I don't know which, if any of these factors are correct, but 16384 is a very interesting number.

**Comment by bigdogmat** [comment]
The appears to be a gmod limitation, considering the Vector object is made in c and not Lua I cannot look at the implementation, however after testing it appears each component is stored as a 16 bit signed integer. This would explain why you can't go over 16384, or below -16384.

**Comment by oskar94** [comment]
net.WriteVector is currently sending the values as a [half precision float](https://en.wikipedia.org/wiki/Half-precision_floating-point_format) and is therefor limited by their size. 
What I will do is write a custom function to send it as a [single precision float](https://en.wikipedia.org/wiki/Single-precision_floating-point_format)  to get values up to 2^31-1.

**Comment by bigdogmat** [comment]
Oh well, you beat me to it
