### ISSUE TITLE
vector.clone() produces invalid vector

### ISSUE THREAD

**Issue by Doubleumc** [Rusketh/ExpAdv2#367]
The vector.clone() command does not create a valid vector.  The following code demonstrates this:
```
server {
    vector Vec = vec(10, 20, 30)
    vector Clone = Original.clone()
    print(Original, Clone)
}
```
This code produces the following output:
```
Vec( 10.00, 20.00, 30.00 )Vec(void, void, void)
```
The cloned vector does not properly exist.  Furthermore, any attempt to interact with the clone, such as with `Clone.setX(10)` throws an error:
```
Expression Advanced 2 - Suffered a serverside Script error:
attempt to reach void
```
Or with `Clone += vec(1, 2, 3)`:
```
Expression Advanced 2 - Suffered a serverside Script error:
EXPADV2:16: bad argument #1 to '__add' (Vector expected, got nil)
```

**Comment by ArmyArmyCz** [comment]
Shouldn't it be vector Clone = Vec.clone()? Since you never define a vector called Original.

**Comment by Doubleumc** [comment]
You're right, I incorrectly copied the test code.  This is what I meant to post:
```
server {
    vector Original = vec(10, 20, 30)
    vector Clone = Original.clone()
    print(Original, Clone)
}
```
This code still gives the results as described.

**Comment by bigdogmat** [comment]
This is because the functions are defined as a prepared, not inline. I'll make a pr tomorrow
