### ISSUE TITLE
Vehicles are not included in table.entityKeys()

### ISSUE THREAD

**Issue by Doubleumc** [Rusketh/ExpAdv2#369]
When a table has a vehicle-type entity used as a key this key does not properly return with the table.entityKeys() function.  The following test code can be used to demonstrate, link the input entity to a pod or vehicle:
```
server {
    input entity Vehicle
    
    table Table = {Vehicle = true}
    array Array = Table.entityKeys()
    
    printTable(Table)
    printArray(Array)
    print(#Array)
    print(Array[1, entity])
}
```
We expect that this entity would be passed to the array, but that does not happen.  Below are the results of this test code:
```
Vehicle [426][prop_vehicle_prisoner_pod]	=	<boolean: true>
0
Expression Advanced 2 - Uncatched Exception (serverside):
array - array reach index 1 returned void
```
Note that `printArray(Array)` does not have its own print line as the array is empty.  The test code functions properly when linked to a normal prop.

**Comment by bigdogmat** [comment]
This would be due to [this](https://github.com/Rusketh/ExpAdv2/blob/f9e53df586f6dd2af714dd7d28e1210aa4f1e68b/lua/expadv/components/table.lua#L206) line, should use `isentity` instead of checking types.
