### ISSUE TITLE
Passing an invalid angle to entity.applyAngForce() will crash your game

### ISSUE THREAD

**Issue by Doubleumc** [Rusketh/ExpAdv2#373]
If you try to apply an angular force using an angle with invalid (`nan`) values, the entire game will crash.  Create a chip with the following code, wire up the input to another prop, and refresh the chip.
```
server {
    input entity Target
    angle BadAngle = ang(acos(2))
    print(BadAngle)
    Target.applyAngForce(BadAngle) //WILL CRASH YOU GAME!
}
```
The game will then crash.  This is consistent and repeatable.  Does not seem to crash if applied to entity() (the chip) instead of an external object.  While I was unwilling to perform such a test, I imagine that doing this on a server would crash the server as well.  I also have several .mdmp crash files available if desired, with the following exception: `"The thread tried to read from or write to a virtual address for which it does not have the appropriate access."`

On an unrelated note I have to say this was actually kind of fun to track down.  So the game crashes sometimes when I run my code.
Why?  Because sometimes the force applied is invalid.
Why?  Because sometimes you rotate it by `nan` degrees.
Why?  Because sometimes you pass a value > 1 to `acos()`.
Why?  Because the dot product between two normalized vectors is sometimes > 1.
Why?  Because normalization isn't perfect, the limitations of precision mean their magnitudes are very close to, but not quite 1.  Sometimes they are over, sometimes under.  Normally such a small variation isn't an issue, unless you're trying to get two vectors to converge and are succeeding, so that their dot product is _very_ close to 1.  Then if the normalization randomly throws out two vectors with magnitudes _slightly_ greater than 1, you get a result > 1.  Bad news down the line!

**Comment by bigdogmat** [comment]
Surprised there wasn't a check set in place, these kind of functions are known to crash when using nan or inf values.

**Comment by bigdogmat** [comment]
@ArmyArmyCz You know Vectors ang Angles don't have IsValid methods, you just broke a shit ton of functions by pushing that

**Comment by oskar94** [comment]
I'll have a look at it and fix it.

**Comment by ArmyArmyCz** [comment]
I've tested it and it worked for me

**Comment by bigdogmat** [comment]
> I've tested it and it worked for me

Did you test it with valid angles and vectors? IsValid returns false regardless of what they contain.

**Comment by ArmyArmyCz** [comment]
Oh I see, I'll revert it.
