### ISSUE TITLE
Delta ($) operator returns negated result

### ISSUE THREAD

**Issue by Doubleumc** [Rusketh/ExpAdv2#374]
When using the `$` operator it correctly returns the expected magnitude of the change, but the sign of the change is not correct.  This can be demonstrated by the following code:
```
server {
    int I; I += 1; print($I)
    vector V; V += 1; print($V)
    vector2 V2; V2 += 1; print($V2)
    angle A; A += 1; print($A)
}
```
Here is the output of the code, which is negative even though all variables were increased.  This is the opposite of what was expected.
```
-1
Vec( -1.00, -1.00, -1.00 )
Vec2( -1, -1 )
<angle: -1.000 -1.000 -1.000>
```
Similarly if the `+=` operators are replaced by `-=` the the results are positive instead.

**Comment by ArmyArmyCz** [comment]
The problem is probably here https://github.com/Rusketh/ExpAdv2/blob/master/lua/expadv/components/number.lua#L87
They should be switched, I'll look into it.
