### ISSUE TITLE
EA2 - Wirelink Help

### ISSUE THREAD

**Issue by MurphyMittens** [Rusketh/ExpAdv2#377]
The other day I discovered EA2. I've never paid any attention to the default text in the E2 window. So for the past two days I've been discontinuing the use of E2 and moved over to EA2. The syntax is a little different, but manageable. The Wiki is fine at most parts, but some parts missing. That is why Im asking this question.

1.
If I wire my EA2 up to a button/screen/whatever, how can I get the return the ENTITY of the thing I've wired to.
In E2 I would simply use "XWL:entity() Returns the entity of the linked component", but I cant find anything like this in the EA2 wiki or Issues or comments or Google...

2.
How do I use Wirelink to trigger inputs/outputs to the component I've connected?
In E2 I would use XWL["Open",number]=1 (When Im using the Wiremod Extra - Door Controller)

I tried to use the wirelink.writeCell(number, number) because thats the closest method I found, but the problem is that it doesnt work/I dont get it/there is no such thing/oh wait, there is such a thing, but Im looking in the wrong place

If anyone has some examples, that would me smashing!

Send help!

──────────────███████──███████
──────────████▓▓▓▓▓▓████░░░░░██
────────██▓▓▓▓▓▓▓▓▓▓▓▓██░░░░░░██
──────██▓▓▓▓▓▓████████████░░░░██
────██▓▓▓▓▓▓████████████████░██
────██▓▓████░░░░░░░░░░░░██████
──████████░░░░░░██░░██░░██▓▓▓▓██
──██░░████░░░░░░██░░██░░██▓▓▓▓██
██░░░░██████░░░░░░░░░░░░░░██▓▓██
██░░░░░░██░░░░██░░░░░░░░░░██▓▓██
──██░░░░░░░░░███████░░░░██████
────████░░░░░░░███████████▓▓██
──────██████░░░░░░░░░░██▓▓▓▓██
────██▓▓▓▓██████████████▓▓██
──██▓▓▓▓▓▓▓▓████░░░░░░████
████▓▓▓▓▓▓▓▓██░░░░░░░░░░██
████▓▓▓▓▓▓▓▓██░░░░░░░░░░██
██████▓▓▓▓▓▓▓▓██░░░░░░████████
──██████▓▓▓▓▓▓████████████████
────██████████████████████▓▓▓▓██
──██▓▓▓▓████████████████▓▓▓▓▓▓██
████▓▓██████████████████▓▓▓▓▓▓██
██▓▓▓▓██████████████████▓▓▓▓▓▓██
██▓▓▓▓██████████──────██▓▓▓▓████
██▓▓▓▓████──────────────██████ 
──████

**Comment by Rusketh** [comment]
`server {
	input wirelink WireIO;

	//We can cast a wirelink down to an entity object.
	entity WireEnt = (entity) WireIO;

	//Use a wirelink in EA2 the same as in E2.
	WireIO["On", number] = 1;
}`

It is also possible to omit the casting operator as EA2 is capable of making casting decisions for you in certain places (such as assignments).

`entity WireEnt = WireIO;
//EA2 will see your trying to assign a wire-link to an entity var.
//Because the wire-link can be casted to an entity instead of error EA" will do this for you. `

**Comment by MurphyMittens** [comment]
This is brilliant! I love this place already

░░░░░▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░
 ░░░▓▓▓▓▓▓▒▒▒▒▒▒▓▓░░░░░░░ 
░░▓▓▓▓▒░░▒▒▓▓▒▒▓▓▓▓░░░░░ 
░▓▓▓▓▒░░▓▓▓▒▄▓░▒▄▄▄▓░░░░ 
▓▓▓▓▓▒░░▒▀▀▀▀▒░▄░▄▒▓▓░░░ 
▓▓▓▓▓▒░░▒▒▒▒▒▓▒▀▒▀▒▓▒▓░░ 
▓▓▓▓▓▒▒░░░▒▒▒░░▄▀▀▀▄▓▒▓░ 
▓▓▓▓▓▓▒▒░░░▒▒▓▀▄▄▄▄▓▒▒▒▓ 
░▓█▀▄▒▓▒▒░░░▒▒░░▀▀▀▒▒▒▒░ 
░░▓█▒▒▄▒▒▒▒▒▒▒░░▒▒▒▒▒▒▓░ 
░░░▓▓▓▓▒▒▒▒▒▒▒▒░░░▒▒▒▓▓░ 
░░░░░▓▓▒░░▒▒▒▒▒▒▒▒▒▒▒▓▓░ 
░░░░░░▓▒▒░░░░▒▒▒▒▒▒▒▓▓░░

**Comment by MurphyMittens** [comment]
So I gave the EGP3 the middle finger and started to use the ExpAdv2 Screen. It cool, its nice. but what is going on...

Every time Im trying to change the size of anything, it just changed the position.

# 1.
Im using ExpAdv2 with a resolution of 1024. It makes things crisp and sexy. Trying to change the size of dlabel, dnumslider, dcheckbox...

dframe Frame = dframe()
...
dlabel Label = dlabel(Frame)
Label.setSize(vec2(100,100)) -> changes the position

dcheckbox Check = dcheckbox(Frame)
Check.setSize(vec2(100,100)) -> Does nothing

 dnumslider Slider = dnumslider(Frame)
Slider.setSize(vec2(100,200))

**Comment by MurphyMittens** [comment]
So I gave the EGP3 the middle finger and started to use the ExpAdv2 Screen. It cool, its nice. but what is going on...

Every time Im trying to change the size of anything, its just changing the position.


# 1.
Im using ExpAdv2 with a resolution of 1024. It makes things crisp and sexy, but too tiny. Trying to change the size of dlabel, dnumslider, dcheckbox...

dframe Frame = dframe()
...
dlabel Label = dlabel(Frame)
           Label.setSize(vec2(100,100)) -> changes the position

dcheckbox Check = dcheckbox(Frame)
            Check.setSize(vec2(100,100)) -> Does nothing

dnumslider Slider = dnumslider(Frame)
             Slider.setSize(vec2(100,100))  -> ??? (changes the position too...)


# 2. 
Is it possible to change the color of the generic default gray "Frame box", and other things ?

# 3. 
What is going on with the Slider. It makes my view spass around sometimes, and the arrow thingy you press to change the value is soooo tiny.



░░█▀░░░░░░░░░░░▀▀███████░░░░ ░
░█▌░░░░░░░░░░░░░░░▀██████░░░ ░
█▌░░░░░░░░░░░░░░░░███████▌░░ ░
█░░░░░░░░░░░░░░░░░████████░░ 
▐▌░░░░░░░░░░░░░░░░░▀██████▌░░ 
░▌▄███▌░░░░▀████▄░░░░▀████▌░░ 
▐▀▀▄█▄░▌░░░▄██▄▄▄▀░░░░████▄▄░ 
▐░▀░░═▐░░░░░░══░░▀░░░░▐▀░▄▀▌▌ 
▐░░░░░▌░░░░░░░░░░░░░░░▀░▀░░▌▌ 
▐░░░▄▀░░░▀░▌░░░░░░░░░░░░▌█░▌▌ 
░▌░░▀▀▄▄▀▀▄▌▌░░░░░░░░░░▐░▀▐▐░
 ░▌░░▌░▄▄▄▄░░░▌░░░░░░░░▐░░▀▐░░
 ░█░▐▄██████▄░▐░░░░░░░░█▀▄▄▀░░
 ░▐░▌▌░░░░░░▀▀▄▐░░░░░░█▌░░░░░░
 ░░█░░▄▀▀▀▀▄░▄═╝▄░░░▄▀░▌░░░░░░ There's clearly something I've done wrong.
 ░░░▌▐░░░░░░▌░▀▀░░▄▀░░▐░░░░░░░ If anyone is reading this, know that YOU'RE awesome
░░░▀▄░░░░░░░░░▄▀▀░░░░█░░░░░░░ 
░░░▄█▄▄▄▄▄▄▄▀▀░░░░░░░▌▌░░░░░░
 ░░▄▀▌▀▌░░░░░░░░░░░░░▄▀▀▄░░░░░ I have a feeling this isnt the place to ask questions?
 ▄▀░░▌░▀▄░░░░░░░░░░▄▀░░▌░▀▄░░░ 
 ░░░░▌█▄▄▀▄░░░░░░▄▀░░░░▌░░░▌▄▄
 ░░░▄▐██████▄▄░▄▀░░▄▄▄▄▌░░░░▄░
 ░░▄▌████████▄▄▄███████▌░░░░░▄
 ░▄▀░██████████████████▌▀▄░░░░ 
▀░░░█████▀▀░░░▀███████░░░▀▄░░ 
░░░░▐█▀░░░▐░░░░░▀████▌░░░░▀▄░ 
░░░░░░▌░░░▐░░░░▐░░▀▀█░░░░░░░▀ 
░░░░░░▐░░░░▌░░░▐░░░░░▌░░░░░░░
