### ISSUE TITLE
Server crash using setInertia

### ISSUE THREAD

**Issue by Extra-Mental** [Rusketh/ExpAdv2#386]
I was playing with setInertia on a server and whenever I used it on a prop, it would just disappear. I thought it was just too sensitive so i decided to move to decimals below 1. Once I spawned it on the prop, the server crashed, when it came back, I tried again and it instantly crashed again.

I used it on the PHX cube1x1x1 with the following code.

```
server{
    
    entity().isWeldedTo().setInertia(vec(0,0,0.0000000000000001))
    
}
```

**Comment by oskar94** [comment]
Crash was from setting the inertia to a 0 value on any axis, and also with extremely small values.
