### ISSUE TITLE
playerChat event no longer shared?

### ISSUE THREAD

**Issue by Extra-Mental** [Rusketh/ExpAdv2#387]
The event playerChat was changed to client side only? Was this supposed to happen?

**Comment by bigdogmat** [comment]
For some reason in 8038e08f207a08b464162193c5d192ae06d02837 @oskar94 changed it to client side even though it still has a server side caller.

**Comment by oskar94** [comment]
I was fixing some event being registered wrongly and missed that there was two hooks doing the playerChat event and made a mistake will be fixed in a few min.

**Comment by oskar94** [comment]
a121bfd109db141a7e7e9f552ab0907e25c15961 supposed to point to this issue.
