### ISSUE TITLE
Problem with HSV color

### ISSUE THREAD

**Issue by ArmyArmyCz** [Rusketh/ExpAdv2#390]
Currently rgb2hsv takes a color, which is a LUA color. Problem with that, is LUA limits the R,G,B, and A values to 255. I'm not sure what to do about this, I guess the Color object would need to be modified?

**Comment by bigdogmat** [comment]
The color object isn't the issue, `hsv2rgb` shouldn't take a color object as an argument.

**Comment by ArmyArmyCz** [comment]
That's what I thought first time I saw the change, but then I realized that he probably intended to have "hsv" color format as in color(hue,saturation,value). But looking back at it, I don't see why that would be a thing.

**Comment by bigdogmat** [comment]
Afaik the color object is representative of the rgb color format, and as said should have limits for that format. While this could be used to represent other data, it can't represent hsv, reason being is that hue can go outside the limit (up to 359)

**Comment by ArmyArmyCz** [comment]
Alright, I'll revert the change, I supose rgb2hsv should also be reverted because it now returns a color, which as said shouldn't work because of the limit.

**Comment by bigdogmat** [comment]
Actually, `rgb2hsv` should take a color and return 3 arguments. `hsv2rgb` should take 3 arguments and return a color

**Comment by ArmyArmyCz** [comment]
Yea I'm having troubles with that, as I don't know how to create a EA2 table and return it. I supose returning a table with h,s,v keys would be the right approach?

**Comment by bigdogmat** [comment]
ExpAdv2 has multiple argument return right?

**Comment by ArmyArmyCz** [comment]
I afraid not, I tried it but that's not a thing.

**Comment by bigdogmat** [comment]
Hmm, weird, I remember using it at some point.

Well, you have 2 options then, varargs, or return an array like so

```lua
return{__type = "number", $ColorToHSV(@value 1.r, @value 1.g, @value 1.b)}
```

**Comment by oskar94** [comment]
When i did this i thought that the values was limited to 255, and due to not being able to do multiple returns i chose to return a color.
