### ISSUE TITLE
Would it be possible to support object-oriented programming?

### ISSUE THREAD

**Issue by TouristZ** [Rusketh/ExpAdv2#391]
Hello. From my experiences using EA2, I have noticed that there is a class keyword, however you are not able to create your own classes and instantiate them as objects.

EA2 appears to be able to support OOP. For example, the player type inherits from entity, according to the manual. Also, entity and player both have methods, such as entity.model() and player.steamID() respectively. These are all OOP Concepts, but you are not able to actually write your own classes and instantiate them.

I mean maybe this is a stupid question and I probably don't know what I'm talking about, but would it be possible to support OOP in EA2?

**Comment by Rusketh** [comment]
This has been requested several times and whilst we originally planned for this feature as we have explained many a time its just not possible.

**Comment by szymski** [comment]
It is possible.
